// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "swiftuiweb",
    platforms: [
        .macOS("11.0"),
        .iOS("13.0")
    ],
    products: [
        .executable(
            name: "swiftuiweb",
            targets: ["swiftuiweb"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/TokamakUI/Tokamak", "0.11.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "swiftuiweb",
            dependencies: [
                "swiftuiwebLibrary",
                .product(name: "TokamakShim", package: "Tokamak")
            ],
            resources: [
                .process("Resources")
            ]
        ),
        .target(
            name: "swiftuiwebLibrary"
        ),
        .testTarget(
            name: "swiftuiwebLibraryTests",
            dependencies: [
                "swiftuiwebLibrary"
            ]
        )
    ]
)